name: Unity Windows Build

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build Windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Git LFS files
        run: |
          git lfs pull
          git add .
          git reset --hard
      
      - name: Check repository status
        run: git status --short

      - name: Build Unity project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: build
